name: Test Report

on:
  workflow_run:
    workflows: ["Build and Release"]
    types:
      - completed

permissions:
  checks: write
  actions: read

jobs:
  report:
    name: Publish Test Results
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
        continue-on-error: true

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: hashFiles('test-results.xml') != ''
        with:
          name: Test Results (${{ matrix.os }})
          path: test-results.xml
          reporter: java-junit
